name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests-2:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    - name: set 0 user
      run: npm config set user 0
    - name: config npm
      run: npm config set unsafe-perm true
    - name: npm install and run
      run: npm install & npm run dev
